name: commit_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: abystoma/external-workflow@branch
        with:
          ref: branch
      - name: Greetings
        run: echo "$(
